---
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - /path/to/library:/config
      - path/to/tvseries:/tv
      - /path/to/movies:/movies
      - /path for transcoding:/transcode
    restart: unless-stopped
