version: '2'

services:
  plex:
    image: plexinc/pms-docker
    container_name: pms
    # network_mode: host
    environment:
      - VERSION=latest
      - PUID=1000
      - PGID=1000
      - TZ="Europe/London"
      - PLEX_CLAIM="${PLEX_CLAIM}" # https://www.plex.tv/claim/
    volumes:
      - "${PWD}/config:/config"
      - "${PWD}/transcode:/transcode"
      - "${DATA}:/data"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
