---
version: "2"
services:
  plex:
    image: linuxserver/plex:arm32v7-latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - /media/plex/config:/config
      - /media/plex/transcode:/transcode
      - /media/plex:/data
    restart: unless-stopped
