---
version: "2"
services:
  plex:
    image: linuxserver/plex:arm32v7-latest
    container_name: plex
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM="${PLEX_CLAIM}" # https://www.plex.tv/claim/
    volumes:
      - /media/plex/config:/config
      - /media/plex/transcode:/transcode
      - /media/plex:/data
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    restart: unless-stopped
